package com.example.ProductService.statics;

public class DefaultProductNames {
    // Fruits and vegetables
    public static final String[] FRUITS_AND_VEGETABLES = {
            "Apple",
            "Apricot",
            "Avocado",
            "Banana",
            "Blackberry",
            "Blackcurrant",
            "Blueberry",
            "Boysenberry",
            "Cherry",
            "Coconut",
            "Cranberry",
            "Cucumber",
            "Currant",
            "Damson",
            "Date",
            "Dragonfruit",
            "Durian",
            "Elderberry",
            "Feijoa",
            "Fig",
            "Goji berry",
            "Gooseberry",
            "Grape",
            "Grapefruit",
            "Guava",
            "Honeyberry",
            "Huckleberry",
            "Jabuticaba",
            "Jackfruit",
            "Jambul",
            "Jujube",
            "Juniper berry",
            "Kiwano",
            "Kiwifruit",
            "Kumquat",
            "Lemon",
            "Lime",
            "Loquat",
            "Longan",
            "Lychee",
            "Mango",
            "Mangosteen",
            "Marionberry",
            "Melon",
            "Cantaloupe",
            "Honeydew",
            "Watermelon",
            "Miracle fruit",
            "Mulberry",
            "Nectarine",
            "Nance",
            "Olive",
            "Orange",
            "Blood orange",
            "Clementine",
            "Mandarine",
            "Tangerine",
            "Papaya",
            "Passionfruit",
            "Peach",
            "Pear",
            "Persimmon",
            "Plantain",
            "Plum",
            "Prune",
            "Pineapple",
            "Pineberry",
            "Plumcot",
            "Pomegranate",
            "Pomelo",
            "Purple mangosteen",
            "Quince",
            "Raspberry",
            "Salmonberry",
            "Rambutan",
            "Redcurrant",
            "Salal berry",
            "Salak",
            "Satsuma",
            "Soursop",
            "Star apple",
            "Star fruit",
            "Strawberry",
            "Surinam cherry",
            "Tamarillo",
            "Tamarind",
            "Ugli fruit",
            "White currant",
            "White sapote",
            "Yuzu",
            "Bell pepper",
            "Chili pepper",
            "Corn kernel",
            "Cucumber",
            "Eggplant",
            "Olive",
            "Pea",
            "Pumpkin",
            "Squash",
            "Tomato",
            "Zucchini",
    };
}
