server:
  port: 9091
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://${AWS_RDS_MYSQL_HOST}/product_service_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${AWS_RDS_MYSQL_USERNAME}
    password: ${AWS_RDS_MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:axonserver}

webhook:
  baseUrl: https://webhook.site/
  endpoint: 44245127-ce8a-44aa-b4cd-184b4c74eb8d
