spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update