spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

aws:
  api:
    gateway:
      url: "https://1q2w3e4r5t.execute-api.us-east-1.amazonaws.com/dev"