server:
  port: 9091
  address: 0.0.0.0

webhook:
  url: https://webhook.site/cff91590-5ce9-47ef-b20f-13a5ab910dac

spring:
  profiles:
    active: dev

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.example.mypackage: DEBUG
