name: Build and Push Docker Image
on:
  workflow_run:
    workflows: [ "Build Java with Maven and Upload Artifact to GitHub" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build --build-arg SPRING_PROFILES_ACTIVE=prod -t cqrs_product_service .

      - name: Tag Docker image
        run: docker tag cqrs_product_service:latest sasha1doc/cqrs_product_service:latest

      - name: Push Docker image to Docker Hub
        run: docker push sasha1doc/cqrs_product_service:latest
